## Use command to compute the size of a matrix, size/length of a particular row/column, load data from a text file, store matrix data to a text file, finding out variables and their features in the current scope.

In [1]:
import numpy as np
import pandas as pd

In [2]:
A = np.array(
    [[1, 2, 3],
     [1,3,2]])

In [3]:
# size of A
A.shape

(2, 3)

In [4]:
# number of elements in row 0
A[0, :].shape

(3,)

In [5]:
# number of elements in column 2
A[:, 2].shape

(2,)

In [6]:
dataset = pd.DataFrame(
    {'Column1': A[:, 0],
     'Column2': A[:, 1],
     'Column3': A[:, 2]})
dataset

   Column1  Column2  Column3
0        1        2        3
1        1        3        2

In [7]:
dataset.to_csv('mydata.txt', header = True, index = False, sep = ',', mode = 'a')

In [8]:
data1 = pd.read_csv('mydata.txt')
data1

   Column1  Column2  Column3
0        1        2        3
1        1        3        2

In [9]:
data = pd.read_csv('ex1data1.txt', names = ["population", "profit"])
data

    population    profit
0       6.1101  17.59200
1       5.5277   9.13020
2       8.5186  13.66200
3       7.0032  11.85400
4       5.8598   6.82330
..         ...       ...
92      5.8707   7.20290
93      5.3054   1.98690
94      8.2934   0.14454
95     13.3940   9.05510
96      5.4369   0.61705

[97 rows x 2 columns]

In [10]:
locals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  'import numpy as np\nimport pandas as pd',
  'A = np.array(\n    [[1, 2, 3],\n     [1,3,2]])',
  '# size of A\nA.shape',
  '# number of elements in row 0\nA[0, :].shape',
  '# number of elements in column 2\nA[:, 2].shape',
  "dataset = pd.DataFrame(\n    {'Column1': A[:, 0],\n     'Column2': A[:, 1],\n     'Column3': A[:, 2]})\ndataset",
  "dataset.to_csv('mydata.txt', header = True, index = False, sep = ',', mode = 'a')",
  "data1 = pd.read_csv('mydata.txt')\ndata1",
  'data = pd.read_csv(\'ex1data1.txt\', names = ["population", "profit"])\ndata',
  'locals()'],
 '_oh': {3: (2, 3),
  4: (3,),
  5: (2,),
  6:    Column1  Column2  Column3
  0        1        2        3
  1        1        3        2,
  8:    Column1  Column2  Column3
  0        1        2        3
  1        1        3        2,
  9:     population    profit
  0       6.1101  17.59200
  1       5.5277   9.13020
  2       8.5186  13.66200
  3       7.0032  11.85400
  4       5.8598   6.82330
  ..         ...       ...
  92      5.8707   7.20290
  93      5.3054   1.98690
  94      8.2934   0.14454
  95     13.3940   9.05510
  96      5.4369   0.61705

  [97 rows x 2 columns]},
 '_dh': ["C:\\Users\\Shashank\\Parag's ML Practicals"],
 'In': ['',
  'import numpy as np\nimport pandas as pd',
  'A = np.array(\n    [[1, 2, 3],\n     [1,3,2]])',
  '# size of A\nA.shape',
  '# number of elements in row 0\nA[0, :].shape',
  '# number of elements in column 2\nA[:, 2].shape',
  "dataset = pd.DataFrame(\n    {'Column1': A[:, 0],\n     'Column2': A[:, 1],\n     'Column3': A[:, 2]})\ndataset",
  "dataset.to_csv('mydata.txt', header = True, index = False, sep = ',', mode = 'a')",
  "data1 = pd.read_csv('mydata.txt')\ndata1",
  'data = pd.read_csv(\'ex1data1.txt\', names = ["population", "profit"])\ndata',
  'locals()'],
 'Out': {3: (2, 3),
  4: (3,),
  5: (2,),
  6:    Column1  Column2  Column3
  0        1        2        3
  1        1        3        2,
  8:    Column1  Column2  Column3
  0        1        2        3
  1        1        3        2,
  9:     population    profit
  0       6.1101  17.59200
  1       5.5277   9.13020
  2       8.5186  13.66200
  3       7.0032  11.85400
  4       5.8598   6.82330
  ..         ...       ...
  92      5.8707   7.20290
  93      5.3054   1.98690
  94      8.2934   0.14454
  95     13.3940   9.05510
  96      5.4369   0.61705

  [97 rows x 2 columns]},
 'get_ipython': <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x000002349876AF88>>,
 'exit': <IPython.core.autocall.ZMQExitAutocall at 0x2349889dd88>,
 'quit': <IPython.core.autocall.ZMQExitAutocall at 0x2349889dd88>,
 '_':     population    profit
 0       6.1101  17.59200
 1       5.5277   9.13020
 2       8.5186  13.66200
 3       7.0032  11.85400
 4       5.8598   6.82330
 ..         ...       ...
 92      5.8707   7.20290
 93      5.3054   1.98690
 94      8.2934   0.14454
 95     13.3940   9.05510
 96      5.4369   0.61705

 [97 rows x 2 columns],
 '__':    Column1  Column2  Column3
 0        1        2        3
 1        1        3        2,
 '___':    Column1  Column2  Column3
 0        1        2        3
 1        1        3        2,
 '_i': 'data = pd.read_csv(\'ex1data1.txt\', names = ["population", "profit"])\ndata',
 '_ii': "data1 = pd.read_csv('mydata.txt')\ndata1",
 '_iii': "dataset.to_csv('mydata.txt', header = True, index = False, sep = ',', mode = 'a')",
 '_i1': 'import numpy as np\nimport pandas as pd',
 'np': <module 'numpy' from 'C:\\Users\\Shashank\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>,
 'pd': <module 'pandas' from 'C:\\Users\\Shashank\\Anaconda3\\lib\\site-packages\\pandas\\__init__.py'>,
 '_i2': 'A = np.array(\n    [[1, 2, 3],\n     [1,3,2]])',
 'A': array([[1, 2, 3],
        [1, 3, 2]]),
 '_i3': '# size of A\nA.shape',
 '_3': (2, 3),
 '_i4': '# number of elements in row 0\nA[0, :].shape',
 '_4': (3,),
 '_i5': '# number of elements in column 2\nA[:, 2].shape',
 '_5': (2,),
 '_i6': "dataset = pd.DataFrame(\n    {'Column1': A[:, 0],\n     'Column2': A[:, 1],\n     'Column3': A[:, 2]})\ndataset",
 'dataset':    Column1  Column2  Column3
 0        1        2        3
 1        1        3        2,
 '_6':    Column1  Column2  Column3
 0        1        2        3
 1        1        3        2,
 '_i7': "dataset.to_csv('mydata.txt', header = True, index = False, sep = ',', mode = 'a')",
 '_i8': "data1 = pd.read_csv('mydata.txt')\ndata1",
 'data1':    Column1  Column2  Column3
 0        1        2        3
 1        1        3        2,
 '_8':    Column1  Column2  Column3
 0        1        2        3
 1        1        3        2,
 '_i9': 'data = pd.read_csv(\'ex1data1.txt\', names = ["population", "profit"])\ndata',
 'data':     population    profit
 0       6.1101  17.59200
 1       5.5277   9.13020
 2       8.5186  13.66200
 3       7.0032  11.85400
 4       5.8598   6.82330
 ..         ...       ...
 92      5.8707   7.20290
 93      5.3054   1.98690
 94      8.2934   0.14454
 95     13.3940   9.05510
 96      5.4369   0.61705

 [97 rows x 2 columns],
 '_9':     population    profit
 0       6.1101  17.59200
 1       5.5277   9.13020
 2       8.5186  13.66200
 3       7.0032  11.85400
 4       5.8598   6.82330
 ..         ...       ...
 92      5.8707   7.20290
 93      5.3054   1.98690
 94      8.2934   0.14454
 95     13.3940   9.05510
 96      5.4369   0.61705

 [97 rows x 2 columns],
 '_i10': 'locals()'}

In [11]:
globals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  'import numpy as np\nimport pandas as pd',
  'A = np.array(\n    [[1, 2, 3],\n     [1,3,2]])',
  '# size of A\nA.shape',
  '# number of elements in row 0\nA[0, :].shape',
  '# number of elements in column 2\nA[:, 2].shape',
  "dataset = pd.DataFrame(\n    {'Column1': A[:, 0],\n     'Column2': A[:, 1],\n     'Column3': A[:, 2]})\ndataset",
  "dataset.to_csv('mydata.txt', header = True, index = False, sep = ',', mode = 'a')",
  "data1 = pd.read_csv('mydata.txt')\ndata1",
  'data = pd.read_csv(\'ex1data1.txt\', names = ["population", "profit"])\ndata',
  'locals()',
  'globals()'],
 '_oh': {3: (2, 3),
  4: (3,),
  5: (2,),
  6:    Column1  Column2  Column3
  0        1        2        3
  1        1        3        2,
  8:    Column1  Column2  Column3
  0        1        2        3
  1        1        3        2,
  9:     population    profit
  0       6.1101  17.59200
  1       5.5277   9.13020
  2       8.5186  13.66200
  3       7.0032  11.85400
  4       5.8598   6.82330
  ..         ...       ...
  92      5.8707   7.20290
  93      5.3054   1.98690
  94      8.2934   0.14454
  95     13.3940   9.05510
  96      5.4369   0.61705

  [97 rows x 2 columns],
  10: {...}},
 '_dh': ["C:\\Users\\Shashank\\Parag's ML Practicals"],
 'In': ['',
  'import numpy as np\nimport pandas as pd',
  'A = np.array(\n    [[1, 2, 3],\n     [1,3,2]])',
  '# size of A\nA.shape',
  '# number of elements in row 0\nA[0, :].shape',
  '# number of elements in column 2\nA[:, 2].shape',
  "dataset = pd.DataFrame(\n    {'Column1': A[:, 0],\n     'Column2': A[:, 1],\n     'Column3': A[:, 2]})\ndataset",
  "dataset.to_csv('mydata.txt', header = True, index = False, sep = ',', mode = 'a')",
  "data1 = pd.read_csv('mydata.txt')\ndata1",
  'data = pd.read_csv(\'ex1data1.txt\', names = ["population", "profit"])\ndata',
  'locals()',
  'globals()'],
 'Out': {3: (2, 3),
  4: (3,),
  5: (2,),
  6:    Column1  Column2  Column3
  0        1        2        3
  1        1        3        2,
  8:    Column1  Column2  Column3
  0        1        2        3
  1        1        3        2,
  9:     population    profit
  0       6.1101  17.59200
  1       5.5277   9.13020
  2       8.5186  13.66200
  3       7.0032  11.85400
  4       5.8598   6.82330
  ..         ...       ...
  92      5.8707   7.20290
  93      5.3054   1.98690
  94      8.2934   0.14454
  95     13.3940   9.05510
  96      5.4369   0.61705

  [97 rows x 2 columns],
  10: {...}},
 'get_ipython': <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x000002349876AF88>>,
 'exit': <IPython.core.autocall.ZMQExitAutocall at 0x2349889dd88>,
 'quit': <IPython.core.autocall.ZMQExitAutocall at 0x2349889dd88>,
 '_': {...},
 '__':     population    profit
 0       6.1101  17.59200
 1       5.5277   9.13020
 2       8.5186  13.66200
 3       7.0032  11.85400
 4       5.8598   6.82330
 ..         ...       ...
 92      5.8707   7.20290
 93      5.3054   1.98690
 94      8.2934   0.14454
 95     13.3940   9.05510
 96      5.4369   0.61705

 [97 rows x 2 columns],
 '___':    Column1  Column2  Column3
 0        1        2        3
 1        1        3        2,
 '_i': 'locals()',
 '_ii': 'data = pd.read_csv(\'ex1data1.txt\', names = ["population", "profit"])\ndata',
 '_iii': "data1 = pd.read_csv('mydata.txt')\ndata1",
 '_i1': 'import numpy as np\nimport pandas as pd',
 'np': <module 'numpy' from 'C:\\Users\\Shashank\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>,
 'pd': <module 'pandas' from 'C:\\Users\\Shashank\\Anaconda3\\lib\\site-packages\\pandas\\__init__.py'>,
 '_i2': 'A = np.array(\n    [[1, 2, 3],\n     [1,3,2]])',
 'A': array([[1, 2, 3],
        [1, 3, 2]]),
 '_i3': '# size of A\nA.shape',
 '_3': (2, 3),
 '_i4': '# number of elements in row 0\nA[0, :].shape',
 '_4': (3,),
 '_i5': '# number of elements in column 2\nA[:, 2].shape',
 '_5': (2,),
 '_i6': "dataset = pd.DataFrame(\n    {'Column1': A[:, 0],\n     'Column2': A[:, 1],\n     'Column3': A[:, 2]})\ndataset",
 'dataset':    Column1  Column2  Column3
 0        1        2        3
 1        1        3        2,
 '_6':    Column1  Column2  Column3
 0        1        2        3
 1        1        3        2,
 '_i7': "dataset.to_csv('mydata.txt', header = True, index = False, sep = ',', mode = 'a')",
 '_i8': "data1 = pd.read_csv('mydata.txt')\ndata1",
 'data1':    Column1  Column2  Column3
 0        1        2        3
 1        1        3        2,
 '_8':    Column1  Column2  Column3
 0        1        2        3
 1        1        3        2,
 '_i9': 'data = pd.read_csv(\'ex1data1.txt\', names = ["population", "profit"])\ndata',
 'data':     population    profit
 0       6.1101  17.59200
 1       5.5277   9.13020
 2       8.5186  13.66200
 3       7.0032  11.85400
 4       5.8598   6.82330
 ..         ...       ...
 92      5.8707   7.20290
 93      5.3054   1.98690
 94      8.2934   0.14454
 95     13.3940   9.05510
 96      5.4369   0.61705

 [97 rows x 2 columns],
 '_9':     population    profit
 0       6.1101  17.59200
 1       5.5277   9.13020
 2       8.5186  13.66200
 3       7.0032  11.85400
 4       5.8598   6.82330
 ..         ...       ...
 92      5.8707   7.20290
 93      5.3054   1.98690
 94      8.2934   0.14454
 95     13.3940   9.05510
 96      5.4369   0.61705

 [97 rows x 2 columns],
 '_i10': 'locals()',
 '_10': {...},
 '_i11': 'globals()'}