In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, StratifiedKFold

In [3]:
df = pd.read_csv("IMDb database.csv")
df

,Title,Release Date,Color,Genre,Language,Country,Rating,Lead Actor,Director Name,Lead Actor FB Likes,Cast FB Likes,Director FB Likes,Movie FB Likes,IMDb Score,Total Reviews,Duration,Gross Revenue,Budget,number of titles
0,Over the Hill to the Poorhouse,9-15-1920,Black and White,Crime,English,USA,Not Rated,Stephen Carr,Harry F. Millarde,2.0,4,0,0,8.4,1.0,110.0,3000000,100000,1
1,Metropolis,1-26-1927,Black and White,Drama,German,Germany,Not Rated,Brigitte Helm,Fritz Lang,136.0,203,756,12000,8.3,260.0,145.0,26435,6000000,1
2,The Broadway Melody,11-11-1929,Black and White,Musical,English,USA,Passed,Anita Page,Harry Beaumont,77.0,109,4,167,6.3,36.0,100.0,2808000,379000,1
3,42nd Street,8-29-1933,Black and White,Comedy,English,USA,Unrated,Ginger Rogers,Lloyd Bacon,610.0,995,24,439,7.7,65.0,89.0,2300000,439000,1
4,Top Hat,4-15-1935,Black and White,Comedy,English,USA,Approved,Ginger Rogers,Mark Sandrich,610.0,824,10,1000,7.8,66.0,81.0,3000000,609000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3728,Sugar Rush,11-11-2016,Color,Comedy,English,USA,PG,Karen Trout,Humberto Guava,431.0,673,22,18363,6.3,433.0,100.0,2808000,379000,1
3729,Why is Grandma Laughing?,8-29-2016,Color,Mystery,English,USA,PG-13,Yulia Velasquez,Purd Haply,86.0,623,1,4771,7.7,110.0,89.0,1700000,439000,1
3730,Luke Warm Soup,4-15-2016,Color,Horror,English,USA,R,Skeeter McGavin,Nick Winkle,167.0,659,20,14580,9.3,209.0,81.0,3000000,609000,1
3731,Clown Parade III,6-1-2016,Color,Comedy,English,USA,PG,Stan Pancake,Todd Waffle,444.0,900,11,15977,4.2,172.0,112.0,3250000,500000,1
3732,Gene's Genes,8-11-2016,Color,Sci-Fi,Spanish,Spain,PG,Randy Killnose,August Clementine,406.0,879,6,10949,6.6,123.0,121.0,1980000,250000,1

In [4]:
df = df.dropna()
df = df.reset_index(drop=True)

In [5]:
df1 = df.copy()
df1["color_bool"] = df1["Color"].map({'Color':True ,'Black and White':False})

In [6]:
df1.color_bool = df1.color_bool.fillna(False)

In [7]:
df1["color_bool"].isnull().sum()

0

In [8]:
X = df1.drop(["color_bool"], axis=1)
Y = df1.color_bool
X_Train, X_Test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state=42, shuffle =True,stratify= Y)

In [9]:
X_Train

,Title,Release Date,Color,Genre,Language,Country,Rating,Lead Actor,Director Name,Lead Actor FB Likes,Cast FB Likes,Director FB Likes,Movie FB Likes,IMDb Score,Total Reviews,Duration,Gross Revenue,Budget,number of titles
1697,A Home at the End of the World,5-13-2004,Color,Drama,English,USA,R,Robin Wright,Michael Mayer,18000.0,21107,15,1000,6.8,84.0,97.0,1029017,6500000,1
3124,Fun Size,10-24-2012,Color,Adventure,English,USA,PG-13,Thomas McDonell,Josh Schwartz,962.0,3715,90,0,5.4,77.0,86.0,9402410,14000000,1
3325,Oblivion,10-4-2013,Color,Action,English,USA,PG-13,Morgan Freeman,Joseph Kosinski,11000.0,22004,364,71000,7.0,539.0,124.0,89021735,120000000,1
1190,All the Queen's Men,12-18-2001,Color,Action,English,Germany,PG-13,Eddie Izzard,Stefan Ruzowitzky,776.0,1732,24,193,4.5,19.0,105.0,22723,25000000,1
2288,Hostel: Part II,7-13-2007,Color,Horror,English,USA,R,Jay Hernandez,Eli Roth,1000.0,4707,0,0,5.4,252.0,94.0,17544812,10000000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2595,Brothers,4-5-2009,Color,Drama,English,USA,R,Natalie Portman,Jim Sheridan,20000.0,42473,260,10000,7.1,217.0,105.0,28501651,26000000,1
572,Executive Decision,3-29-1996,Color,Action,English,USA,R,Oliver Platt,Stuart Baird,1000.0,2916,53,0,6.4,60.0,133.0,68750000,55000000,1
1617,Mona Lisa Smile,8-12-2003,Color,Drama,English,USA,PG-13,Julia Roberts,Mike Newell,8000.0,12850,179,0,6.4,141.0,117.0,63695760,65000000,1
2133,Littleman,6-30-2006,Color,Comedy,English,USA,PG-13,Chazz Palminteri,Keenen Ivory Wayans,979.0,6334,322,0,4.3,78.0,98.0,58255287,64000000,1
612,Sling Blade,9-22-1996,Color,Drama,English,USA,R,Robert Duvall,Billy Bob Thornton,3000.0,3967,0,0,8.0,104.0,148.0,24475416,890000,1

In [10]:
X_Test

,Title,Release Date,Color,Genre,Language,Country,Rating,Lead Actor,Director Name,Lead Actor FB Likes,Cast FB Likes,Director FB Likes,Movie FB Likes,IMDb Score,Total Reviews,Duration,Gross Revenue,Budget,number of titles
3099,Blue Like Jazz,6-12-2012,Color,Comedy,English,USA,PG-13,Jason Marsden,Steve Taylor,1000.0,1805,14,0,6.0,38.0,108.0,594904,1200000,1
3473,Mr. Peabody & Sherman,2-27-2014,Color,Adventure,English,USA,PG,Ty Burrell,Rob Minkoff,3000.0,5810,50,11000,6.9,196.0,92.0,111505642,145000000,1
2459,Mirrors,7-30-2008,Color,Horror,English,USA,R,Jason Flemyng,Alexandre Aja,1000.0,3185,192,5000,6.2,208.0,112.0,30691439,35000000,1
1773,Little Black Book,12-14-2004,Color,Comedy,English,USA,PG-13,Holly Hunter,Nick Hurran,1000.0,4369,34,484,5.2,73.0,105.0,20422207,35000000,1
2919,A Very Harold & Kumar 3D Christmas,1-14-2011,Color,Adventure,English,USA,R,Patton Oswalt,Todd Strauss-Schulson,786.0,2462,12,21000,6.3,161.0,90.0,35033759,19000000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
542,The Quick and the Dead,4-11-1995,Black and White,Action,English,Japan,R,Leonardo DiCaprio,Sam Raimi,29000.0,29743,0,0,6.4,63.0,107.0,18636537,32000000,1
3552,Aloha,2-7-2015,Color,Comedy,English,USA,PG-13,Emma Stone,Cameron Crowe,15000.0,44037,488,11000,5.4,138.0,105.0,20991497,37000000,1
317,Mo' Better Blues,3-3-1990,Color,Drama,English,USA,R,Denzel Washington,Spike Lee,18000.0,19065,0,720,6.5,23.0,129.0,16153600,10000000,1
1148,The Ladies Man,10-27-2000,Color,Comedy,English,USA,R,Will Ferrell,Reginald Hudlin,8000.0,10982,71,671,5.1,58.0,84.0,13592872,11000000,1
1712,Beyond the Sea,1-7-2004,Black and White,Biography,English,USA,PG-13,Kevin Spacey,Kevin Spacey,18000.0,23689,18000,0,6.7,113.0,118.0,6144806,23000000,1

In [11]:
y_train

1697    True
3124    True
3325    True
1190    True
2288    True
        ...
2595    True
572     True
1617    True
2133    True
612     True
Name: color_bool, Length: 2944, dtype: bool

In [12]:
y_test

3099     True
3473     True
2459     True
1773     True
2919     True
        ...
542     False
3552     True
317      True
1148     True
1712    False
Name: color_bool, Length: 736, dtype: bool